# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# my-MemoryPool v3 (git submodule: third_party/my-MemoryPool)
KAMA_MP_ROOT = $$PWD/../../../third_party/my-MemoryPool/v3

HEADERS += ../UI/ivideocallback.h \
    ../UI/isubtitlecallback.h \
    ../UI/playlistmodel.h \
    ../UI/onlinecatalog.h \
    ../UI/subtitleoverlay.h \
    ../Core/audioplayer.h \
    ../Thread/audiothread.h \
    ../Core/mediadecoder.h \
    ../Thread/decodethread.h \
    ../Core/mediademuxer.h \
    ../Thread/demuxthread.h \
    ../Core/audioresampler.h \
    ../Thread/videothread.h \
    ../Thread/subtitlethread.h \
    ../UI/mediaplayer.h \
    ../UI/seekslider.h \
    ../UI/videowidget.h \
    ../../ThreadPool/threadpool.h \
    ../../ThreadPool/GlobalThreadPool.h \
    ../../LockFree/LockFreeQueue.hpp \
    ../../LockFree/LockFreeStack.hpp \
    $$KAMA_MP_ROOT/include/kama/MemoryPool.h \
    $$KAMA_MP_ROOT/include/kama/export.h \
    $$KAMA_MP_ROOT/src/Common.h \
    $$KAMA_MP_ROOT/src/CentralCache.h \
    $$KAMA_MP_ROOT/src/PageCache.h \
    $$KAMA_MP_ROOT/src/ThreadCache.h \
    $$KAMA_MP_ROOT/src/Platform.h

SOURCES += ../Config/main.cpp \
    ../Core/audioplayer.cpp \
    ../Thread/audiothread.cpp \
    ../Core/mediadecoder.cpp \
    ../Thread/decodethread.cpp \
    ../Core/mediademuxer.cpp \
    ../Thread/demuxthread.cpp \
    ../Thread/subtitlethread.cpp \
    ../UI/mediaplayer.cpp \
    ../UI/playlistmodel.cpp \
    ../UI/onlinecatalog.cpp \
    ../UI/subtitleoverlay.cpp \
    ../Core/audioresampler.cpp \
    ../UI/seekslider.cpp \
    ../Thread/videothread.cpp \
    ../UI/videowidget.cpp \
    ../../ThreadPool/threadpool.cpp \
    $$KAMA_MP_ROOT/src/MemoryPool.cpp \
    $$KAMA_MP_ROOT/src/CentralCache.cpp \
    $$KAMA_MP_ROOT/src/PageCache.cpp \
    $$KAMA_MP_ROOT/src/ThreadCache.cpp
