/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1.3-43-g5a1f107b4c-20260408"
#endif /* AVUTIL_FFVERSION_H */
